### PR TITLE
EDA-2953, avoid clkbuf out to drive combinational logic

### PR DESCRIPTION
**Pull request by AYYAZmayo**
@alaindargelas ,under make test/batch_all following tests are clear:
test/batch test/batch_gen2 solver/tests

### CODE REVIEW

**Comment by alaindargelas** [comment]
@AYYAZmayo it is not.
rm -rf and*
make test/batch_all

**Comment by alaindargelas** [comment]
@AYYAZmayo you mean this new PR is working, can you confirm the previous PR was not working?

**Comment by alaindargelas** [comment]
Also copy the 2 bitstream tests from Neulink-Semi repo so you can run all tests.

**Comment by AYYAZmayo** [comment]
> Also copy the 2 bitstream tests from Neulink-Semi repo so you can run all tests.

@alaindargelas , Yes the previous PR was not working and this is updated one with complete testing **test/batch_all** (2 btitstream tests  from Neulink-Semi were also tested).

**Pull request merged**
